services:
  ikea-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ikea-front
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - ikea-network

networks:
  ikea-network:
    external: true
